export const API_ENDPOINTS = {
  AUTH: '/api/auth',
  PORTAL_AUTH: '/api/portal/auth',
  USERS: '/api/admin/users',
  CONTRACTS: '/api/admin/contracts',
  INVOICES: '/api/admin/invoices',
  ROOMS: '/api/admin/rooms',
  BUILDINGS: '/api/admin/buildings',
  METERS: '/api/admin/meters',
  PAYMENTS: '/api/admin/payments',
  TICKETS: '/api/admin/tickets',
  SERVICES: '/api/admin/services',
  ASSETS: '/api/admin/assets',
  DASHBOARD: '/api/admin/dashboard',
  OWNERS: '/api/admin/owners',
  TENANTS: '/api/admin/tenants',
  NOTIFICATIONS: '/api/admin/notifications',
  ANNOUNCEMENTS: '/api/admin/announcements',
  REPORTS: '/api/admin/reports',
  SYSTEM: '/api/admin/system',
  PORTAL: {
    DASHBOARD: '/api/portal/dashboard',
    BALANCE: '/api/portal/balance',
    PROFILE: '/api/portal/profile',
    INVOICES: '/api/portal/invoices',
    TICKETS: '/api/portal/tickets',
    ANNOUNCEMENTS: '/api/portal/announcements',
    AMENITIES: '/api/portal/amenities',
    VISITORS: '/api/portal/visitors',
  }
};
